### ISSUE TITLE
Release cob_extern into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [ipa320/cob_extern#108]
Would you mind releasing `cob_extern` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 12 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by fmessmer** [comment]
thanks for the reminder

I will try to do my best, but cannot promise this to happen too soon...

**Comment by fmessmer** [comment]
https://github.com/ros/rosdistro/pull/25078
