### ISSUE TITLE
Fedora packaging workaround for libntcan

### ISSUE THREAD

**Issue by cottsay** [ipa320/cob_extern#42]
It looks like you're generating RPM spec files as part of your Bloom releases for `cob_extern`. Your package is now available in Fedora Linux, congratulations!

Unfortunately, you're bundling binaries in the `libntcan` package, and this is highly discouraged in RPM packaging. Fortunately, however, there is a workaround!

You'll need to employ Bloom's patching feature to add this workaround. This way, the workaround will get applied to `libntcan` whenever you release the package in `Indigo` automatically. To propagate the patch, releasing the package is required.

To make this easy for you, I made a quick screencast on how to do it: https://www.youtube.com/watch?v=OME9t8PJcyY

After you've run the final `git push` at the end, you'll need to generate a pull request against `ros/rosdistro` with the new version (should now end in -1 instead of -0). Let me know if you have trouble doing this.

Thanks for your help expanding ROS to more platforms!

--scott

**Comment by floweisshardt** [comment]
thanks. Should be fixed with https://github.com/ros/rosdistro/pull/5787. Changes done in https://github.com/ipa320/cob_extern-release/commit/5373a0030c401e3f75d6126c7c80716244e231c4.
