### ISSUE TITLE
code.ros.org url is broken

### ISSUE THREAD

**Issue by tfoote** [ipa320/cob_extern#45]
https://sourceforge.net/p/ros-dry-releases/code/HEAD/tree/download/thirdparty/libphidget_2.1.8.20120716.tar.gz?format=raw

It should be updated to: https://sourceforge.net/p/ros-dry-releases/code/HEAD/tree/download/thirdparty/libphidget_2.1.8.20120716.tar.gz?format=raw

The package can no longer build: http://54.183.26.131:8080/view/Ibin_uT64/job/Ibin_uT64__libphidgets__ubuntu_trusty_amd64__binary/10/console

**Comment by mintar** [comment]
Not sure whether everyone involved is subscribed to the ros-release mailing list, so just as an info: @tfoote posted [a message](http://lists.ros.org/pipermail/ros-release/2015-May/004638.html) that this regression is blocking the next Indigo sync.

In the long run, I guess we should resolve this as discussed in #44. But for now, perhaps it's better to just fix the URL, so the sync can go ahead? I'll send a pull request. @ipa-fmw @muhrix @v4hn

**Comment by fmessmer** [comment]
Thanks for the report...and the solution!

**Comment by benmaidel** [comment]
Thanks to all for fixing this.
