### ISSUE TITLE
libconcorde_tsp_solver does not build on 32bit or arm

### ISSUE THREAD

**Issue by tfoote** [ipa320/cob_extern#65]
This is was added as a dependency of cob_extern and is causing regressions on indigo. 

http://build.ros.org/view/Ibin_uT32/job/Ibin_uT32__libconcorde_tsp_solver__ubuntu_trusty_i386__binary/
http://build.ros.org/view/Ibin_uS32/job/Ibin_uS32__libconcorde_tsp_solver__ubuntu_saucy_i386__binary/
http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_arm_uThf__libconcorde_tsp_solver__ubuntu_trusty_armhf__binary/

http://repositories.ros.org/status_page/ros_indigo_default.html?q=REGRESSION

**Comment by tfoote** [comment]
This is a regression for the upcoming sync: http://discourse.ros.org/t/preparing-indigo-sync-2016-10-21/698

**Comment by floweisshardt** [comment]
temporarily solved in https://github.com/ros/rosdistro/pull/13034 by removing libconcorde_tsp_solver. We'll work on a proper solution for 32bit and release that after the current sync.
