### ISSUE TITLE
asm/linkage.h not found for libpcan on ubuntu 16.04

### ISSUE THREAD

**Issue by tobiasneumann** [ipa320/cob_extern#71]
When this libpcan is build on ubuntu 16.04 with ROS kinetic, asm/linkage.h is not found.
Chaning the following line in file Makefile.tarball fixes the problem

``KERNEL_VER=/usr/src/linux-headers-"`uname -r`"``
to
``KERNEL_VER=/usr/src/linux-headers-"`uname -r`"/arch/x86``

**Comment by fmessmer** [comment]
Could you provide a PR against [kinetic_dev](https://github.com/ipa320/cob_extern/tree/kinetic_dev)

@ipa-bnm have you come across this when testing kinetic?

**Comment by mgruhler** [comment]
see also https://github.com/ipa320/care-o-bot/issues/28

> :x: libphidgets: however there seems to be an error when compiling libphidgets: asm/linkage.h: No such file or directory with kernel 4.4.0-21

**Comment by benmaidel** [comment]
Update to the latest libpcan version (8.3) seems to fix the problem. I will provide a patch.

**Comment by benmaidel** [comment]
@tobiasneumann if you experience unexpected behaviors or errors, please report.

**Comment by fmessmer** [comment]
Closing for the moment...please re-open, if needed
