### ISSUE TITLE
architecture detection relies on dpkg

### ISSUE THREAD

**Issue by languitar** [ipa320/cob_extern#85]
I am currently unable to use this repository without modifications on archlinux as `dpkg` is used to detect the system architecture in various CMake parts. `dpkg` is usually not available on archlinux.

**Comment by fmessmer** [comment]
@languitar 
what kind of adjustments are those?
do you have a suggestion for an alternative approach?

**Comment by languitar** [comment]
I just hacked around that with a static assignment, but `CMAKE_SYSTEM_PROCESSOR` can be used: https://stackoverflow.com/questions/26657082/detect-x86-architecture-in-cmake-file

**Comment by fmessmer** [comment]
would you be willing to provide a PR for this?

**Comment by languitar** [comment]
I gave up on trying this on archlinux.
