### ISSUE TITLE
libdlib and libopengm cannot be installed at the same time

### ISSUE THREAD

**Issue by christian-rauch** [ipa320/cob_extern#87]
The ROS packages `ros-indigo-libopengm` and `ros-indigo-libdlib` try to install `/opt/ros/indigo/include/include/Readme.md`. Therefore both packages cannot be installed at the same time.

I think the packages should not install a `Readme.md` in the include folder anyway.

**Comment by floweisshardt** [comment]
good catch. @ipa-rmb: can you handle that?

**Comment by fmessmer** [comment]
Here is the respective error log:
```
E: /var/cache/apt/archives/ros-indigo-libopengm_0.6.10-0trusty-20170313-063520-0700_amd64.deb: trying to overwrite '/opt/ros/indigo/include/include/Readme.md', which is also in package ros-indigo-libdlib 0.6.10-0trusty-20170313-063613-0700
```

However, the current release 0.6.10 is very old...and we haven't released in quite a while...
In fact, the package ```libopengm``` has been renamed to just ```opengm``` and we use ```cmake```'s ```external_project``` command for installation now

I tested the install from source locally:
there are no ```Readme.md``` installed in the respective ```include``` folders.
Thus, this problem should be solved with the next release...

However, I do not know when this is going to be.
Thus, maybe you can just use cob_extern from source for the time being?

**Comment by ipa-rmb** [comment]
Thanks Felix for sorting that out. I am on travel so no time for testing... sorry.

**Comment by christian-rauch** [comment]
I assume using cob-extern from source in a workspace will workaround this problem.

However, the package `ros-indigo-cob-extern` will still break the package system which is not nice. I am particular interested in having the packages `libpcan` and `libntcan` as a rosdep for easier dependency tracking. At the moment these packages are dependencies of rosdep `cob_extern` which cannot be installed.

Since `cob_extern` is broken in `indigo` and missing in `kinetic` could the current state released to both ROS distros? Alternatively, could you remove `ros-indigo-cob-extern` and release its dependencies (e.g. `libpcan` and `libntcan`) as separate rosdeps?

**Comment by fmessmer** [comment]
a new release is in the pipeline for both [indigo](http://repositories.ros.org/status_page/ros_indigo_default.html?q=cob_extern) and [kinetic](http://repositories.ros.org/status_page/ros_kinetic_default.html?q=cob_extern)
