### ISSUE TITLE
ROS melodic support

### ISSUE THREAD

**Issue by christian-rauch** [ipa320/cob_extern#95]
Is ROS `melodic` already supported? Has someone tried to build `cob_extern` under `melodic`?

I am getting the error: `Invalid configuration x86_64-unknown-linux-gnu: machine x86_64-unknown not recognized` for package `libconcorde_tsp_solver`.

Is this maybe related to the third-party `concorde-tsp-solver`? It seems to be quite old and might not be compatible with newer compilers. I am using gcc 7.3.0.

**Comment by jabbenseth** [comment]
@ipa-rmb how about a partial melodic release without libconcorde-tsp-solver. the solver is not used by any released package (only ipa_room_exploration) so three options come to mind:
- move the package from this repo closer to where it is actually needed
- drop it and all dependees for melodic
- fix it

@fmessmer fyi
