### ISSUE TITLE
libconcorde_tsp_solver build fails on bionic

### ISSUE THREAD

**Issue by christian-rauch** [ipa320/cob_extern#96]
Compiling the `libconcorde_tsp_solver` package on Ubuntu 18.04 / ROS melodic fails with:
``
/usr/bin/ld: [workspace]/build/libconcorde_tsp_solver/libconcorde_tsp_solver-src/libqsopt/qsopt.a(qsopt.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
``

It's the same issue that appears on the meldoic CI: https://travis-ci.org/ipa320/cob_extern/jobs/406770171

I tried to change the cflags in the `ExternalProject` to:
`COMMAND make CFLAGS="-fPIC -shared -I${PROJECT_BINARY_DIR}/${PROJECT_NAME}-src/INCLUDE -I${PROJECT_BINARY_DIR}/${PROJECT_NAME}-src/libqsopt"`
without success.

Any ideas how to successfully compile `libconcorde_tsp_solver` on melodic?

**Comment by christian-rauch** [comment]
The tsp solver build issue is caused by the qsopt binary library.
It can be reproduced outside of catkin by
- downloading [concorde-tsp-solver-20031219.tar.gz](https://github.com/ipa320/thirdparty/raw/master/concorde-tsp-solver-20031219.tar.gz) (or [co031219.tgz](http://www.math.uwaterloo.ca/tsp/concorde/downloads/codes/src/co031219.tgz))
- building with `./configure --with-qsopt=<workspace>/src/cob_extern/libqsopt/common/lib/Qsopt_64`
- `make -j`

Edit: The error only occurs when building the executable, it does not occur when building the library only (`make concorde.a concorde.h`).

**Comment by christian-rauch** [comment]
To summarise, there are three options to solve this issue:
1. do not build with `qsopt`
2. do not build the `concorde` executable (https://github.com/ipa320/cob_extern/pull/97)
3. patch the Concorde TSP Solver Makefile to build the executable with `-fPIC`

**Comment by ipa-rmb** [comment]
Thanks for investigating! I have checked the code which uses concorde. Option 2 can be excluded since the concorde binary is utilized and needed. I have no 18.04 system at hand at the moment and cannot figure out how option 3 would be realized. Hence, option 1 would be ok for now with the new kinetic_dev branch, so we skip libqsopt. If we have more time to investigate this, we will later propose a pull request activating libqsopt again.

**Comment by christian-rauch** [comment]
@ipa-rmb I actually proposed to remove the `concorde` executable in PR https://github.com/ipa320/cob_extern/pull/97.
Can you leave a comment there, where the `concorde` executable is used? If the executable is required, the PR should be closed and be replaced by another one that temporarily disables `qsopt`.

**Comment by ipa-rmb** [comment]
Exactly, I just commented that there and created a new kinetic_dev branch and PR #98 .

**Comment by fmessmer** [comment]
please note that whatever the solution for cob_extern will be, we should merge all melodifying prs required to make the cob-bringup layer melodic-compatible in one swoosh...and not bit by bit...
preferably, followed by a new release for kinetic/melodic

in particular, when changing (default) branches for kinetic in one repo, we might need to adjust `travis.rosinstall` files in downstream repos!

**Comment by fmessmer** [comment]
as an option 4:
why can't we find a `libqsopt` version that satisfies all indigo, kinetic and melodic needs?
where are those `libqsopt` binaries coming from in the first place?
can we build those binaries from source? e.g. include them as a git submodule?

**Comment by christian-rauch** [comment]
I was already looking for a source version, but I only could find this binary distribution: https://www.math.uwaterloo.ca/~bico/qsopt/downloads/downloads.htm.
There is [`qsopt-ex`](https://github.com/jonls/qsopt-ex), but it likely requires source changes to `concorde`.
If you need the `concorde` executable (instead of using the C API in your code) and you want to solve TSP with >10 nodes, it might be easier to patch the concorde Makefile.

@ipa-rmb Are you sure that the `concorde` executable is required in place of the C API? Can you point to the place where the executable is called?

**Comment by ipa-rmb** [comment]
I just met @fmessmer and we discussed that option 4 is probably unlikely, since there is no source code available for qsopt as far as I remember. Anyways, we could go the following roads:
 1. Use the library interface of concorde instead of calling the executable via system call (https://github.com/ipa320/autopnp/blob/de2aa2cb73e7a8e218e340b8b7f0a4ff567cef1a/ipa_building_navigation/common/src/concorde_TSP.cpp#L189).
 1. Try to fix the compiling error of concorde in conjuction with qsopt.
 1. Move all packages and the libraries into a separate repository. We will move ipa_room_exploration, ipa_room_segmentation, and ipa_building_navigation into a single repository anyways and the libraries could go there as well if nobody needs them as standalone in cob_extern.

For all options I would wait for the opinion of @ipa-foj who is currently on vacation. I assume we can get some reply of him by next week.

**Comment by ipa-foj** [comment]
The problem (and the reason why the binary is needed) is that Concorde is written in C and they didn't take a integration in C++ code into account. When building the library, a header is created (concorde.h) that you need to include in your source code to use the interface, but the function signatures sometimes contain identifiers that are reserved keywords in C++ (like "new" or "class"), which means that to my knowledge this won't compile.

But Concorde is not only supporting Qsopt but also CPLEX, which is also free for academic purposes (like Concorde). I think this one is available in 18.04, so it could be another option.

**Comment by christian-rauch** [comment]
Are you using the C block
```C++
extern "C" {
#include <concorde.h>
}
```
to use the C API?

You could use the preprocessor to replace these keywors as suggested in https://stackoverflow.com/a/36869181/8144672. Alternatively, you can manually patch the header `concorde.h` and rename the parameter names.
This will break API with the original header, but it is ABI compatible and you can just link the `concorde.a` afterwards.

**Comment by ipa-foj** [comment]
Thanks for pointing that out, I didn't know this was possible. 

Still after some research it looks like Concorde always requires an LP solver to solve larger TSPs, even when using the C API. It also looks like the Ubuntu 18.04 compatible version of CPLEX is not working with Concorde anymore, due to refactorings that happened. And it might be tricky to integrate Qsopt, as there is no source-code for it.

So I think the option 3 mentioned by @ipa-rmb is the best way to go and thus exclude Qsopt and Concorde from cob_extern for melodic.

**Comment by fmessmer** [comment]
ok, moving the two packages (with history) to a new repo (closer to the packages using them) is ok for me
I'm only wondering which would be the best target branch
I guess we should do this to the `indigo_dev` branch and keep using this branch for both indigo, kinetic and melodic, i.e. the branch `kinetic_dev` could be deleted again
I guess libconcord_tsp_solver was the only package which caused trouble in bionic/melodic, right?
the lib_concord and libqsopt packages will still stay released into indigo and kinetic - by removing it from the repo it does not get un-released...

**Comment by fmessmer** [comment]
@ipa-foj @ipa-rmb 
please suggest a name for the new repo (suitable for the lib packages as well as the application packages using the libs)...you want it to be private (for now - can be made public later) or be public from the beginning
i can then create it and already move the lib packages there...the application packages can follow later (I'll leave that to you)

**Comment by ipa-rmb** [comment]
What about: ipa_navigation_strategies

Are you ok with that repository name, @ipa-jba @ipa-fez @ipa-srd ?
We will put software for (indoor) map segmentation into rooms, efficient room sequencing (TSP), and systematic coverage driving patterns (e.g. track by track and others) into that repository. Falk used parts of this software already successfully. It is currently located in autopnp (ipa_* packages).
Anyways, feel free to suggest another name.

**Comment by ipa-rmb** [comment]
Does anyone has objections against the proposed name in my above comment @ipa-jba @ipa-fez @ipa-srd @fmessmer ? Otherwise, we can take that one.

**Comment by fmessmer** [comment]
`ipa_navigation_strategies` is fine for me...
to confirm: 
 - we will **move (with history)** `libconcorde_tsp_solver` and `libqsopt` form `cob_extern`
 - we will **copy** several ipa packages from an internal project repo, correct?
 - melodic-compatibility is currently not required for that new repo...

**Comment by ipa-rmb** [comment]
All correct, but the second point is slightly different: we will copy (with history) the 4 packages ipa_* from the public project repo https://github.com/ipa320/autopnp .

**Comment by christian-rauch** [comment]
Can a `melodic_dev` branch be created for this repo to remove `libconcorde_tsp_solver` and `libqsopt`?

**Comment by caimingxue** [comment]
How to find "libconcorde_tsp_solver"? I have installed the concorde using qsopt successfully on melodic_dev. but I cannot find the libconcorde_tsp_solver when build autopnp packages.
Please give any hints, Thanks!

**Comment by ipa-foj** [comment]
The "libconcorde_tsp_solver" has been moved to an [individual package](https://github.com/ipa320/ipa_tsp_solvers/). To our knowledge Concorde is just not usable from Bionic on, it is a old library without ongoing support.

**Comment by caimingxue** [comment]
Thanks for your reply, now, I want to install autopnp project on Melodic, what should I do? Is there are any guidelines to follow?
Thanks

**Comment by ipa-rmb** [comment]
Please have a look at the packages here: https://github.com/ipa320/ipa_coverage_planning . The autopnp repository is outdated and we moved the functionality to the new repository. There you can also find a melodic branch which should hopefully work.
